# Generated by Django 3.2.8 on 2022-01-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_fb_login_imgid'),
    ]

    operations = [
        migrations.CreateModel(
            name='seeker_reg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='fb_login',
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
