# Generated by Django 3.2.8 on 2022-01-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220119_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seeker_reg',
            new_name='reg',
        ),
    ]
