# Generated by Django 3.2.8 on 2022-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_seeker_reg_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_reg',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collegename', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
            ],
        ),
    ]
